sudo: required

language: java

jdk: openjdk8

services:
  - docker

install:
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - cd ${TRAVIS_BUILD_DIR}/tests/

env:
  - CLFLAGS=""       # Basic run
  - CLFLAGS="-b"     # Run, example test script flag

script:
  - "./run_test.sh $CLFLAGS"
